let kalimat = "I am going to be React JS Developer";
let kata = kalimat.split(' '); 
console.log('First word: ' + kata[0]);
console.log('Second word: ' + kata[1]);
console.log('Third word: ' + kata[2]);
console.log('Fourth word: ' + kata[3]);
console.log('Fifth word: ' + kata[4]);
console.log('Sixth word: ' + kata[5]);
console.log('Seventh word: ' + kata[6]);
console.log('Eighth word: ' + kata[7]);